import type { Metadata } from "next";
import "./globals.css";
// import db from "@/lib/supabase/db";
import { ThemeProvider } from "@/lib/providers/next-themes-providers";
import {DM_Sans} from 'next/font/google'
import { twMerge } from "tailwind-merge";
import AppStateProvider from "@/lib/providers/state-provider";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = 'force-dynamic'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={twMerge('bg-background',inter.className)}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <AppStateProvider>
          {children}
          </AppStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
